CREATE TABLE job_opportunity_entity
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    event_id    BIGINT,
    CONSTRAINT pk_jobopportunityentity PRIMARY KEY (id)
);

ALTER TABLE job_opportunity_entity
    ADD CONSTRAINT FK_JOBOPPORTUNITYENTITY_ON_EVENT FOREIGN KEY (event_id) REFERENCES event_entity (id);