CREATE TABLE registration_entity
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINTNOT NULL,
    event_id BIGINT NOT NULL,
    CONSTRAINT pk_registrationentity PRIMARY KEY (id)
);

ALTER TABLE registration_entity
    ADD CONSTRAINT FK_REGISTRATIONENTITY_ON_EVENT FOREIGN KEY (event_id) REFERENCES event_entity (id);

ALTER TABLE registration_entity
    ADD CONSTRAINT FK_REGISTRATIONENTITY_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);